### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by johan-lindahl** [MicrosoftDocs/navdevitpro-content-pr#1992]
POST https://{businesscentralPrefix}/api/v1.0/companies({id})/customerPaymentsJournals

should be

POST https://{businesscentralPrefix}/api/v1.0/companies({id})/customerPaymentJournals

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed46ee7-1975-b687-0a70-9efdb11b2261
* Version Independent ID: 5c2f0915-cb21-c840-6f1a-16f227be6437
* Content: [Create customerPaymentsJournals - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_create_customerpaymentsjournal#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_create_customerpaymentsjournal.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_create_customerpaymentsjournal.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - the topic will be fixed with the next doc refresh.
