### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by johan-lindahl** [MicrosoftDocs/navdevitpro-content-pr#1993]
The following example should be correct,

POST https:/{businesscentralPrefix}/api/v1.0/companies({id})/customerPaymentJournals({id})/customerPayments

Note that it is "customerPayments" and not "customerPayment" and that it should be "customerPaymentJournals" and not "customerPaymentsJournals".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 259e1380-ba7b-1af0-1299-d300cc3e7946
* Version Independent ID: 15399408-e77f-edeb-6491-abf1cb6c01fa
* Content: [Create customerPayments - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_create_customerpayment)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_create_customerpayment.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_create_customerpayment.md)
* Service: **dynamics365-financials**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - the topic will be fixed with the next doc refresh.
