### ISSUE TITLE
MyHTMLFile

### ISSUE THREAD

**Issue by mexcelus** [MicrosoftDocs/navdevitpro-content-pr#1995]
The last line of code in the example's snippet should be `MyHTMLFile` instead of `FileMyHTML`.

Regards,
-Guillermo
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0780cc1a-7273-530a-57f8-55668aaa5f6f
* Version Independent ID: e89f9e5f-0ac6-4372-22e8-af04f6b61283
* Content: [OutStream.WRITETEXT Function - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/outstream-writetext-function)
* Content Source: [dynamics-nav/OutStream-WRITETEXT-Function.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/OutStream-WRITETEXT-Function.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, this will be fixed with the next doc refresh, thanks!
