### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/navdevitpro-content-pr#1996]
Item.SetView( filterPagebuilder.Getview('Item Table')); 
 should be
Item.SetView(FilterPagebuilder.Getview('Item Table'));  
  i.e. no space and capital F

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 094843af-2ced-3313-43bf-ca5796be8204
* Version Independent ID: 8d273a4b-3fa7-dc87-8713-38c80544c938
* Content: [Creating Filter Pages for Filtering Tables - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/creating-filter-pages-for-filtering-tables)
* Content Source: [dynamics-nav/Creating-Filter-Pages-for-Filtering-Tables.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Creating-Filter-Pages-for-Filtering-Tables.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, this will be fixed with the next doc refresh, thanks!
