### ISSUE TITLE
Note out of date/incorrect

### ISSUE THREAD

**Issue by hindsight2020** [MicrosoftDocs/navdevitpro-content-pr#2000]
The note
"You also use Microsoft Dynamics NAV 2018 to develop for Dynamics 365 Business Central."
is no more up to date as you use VS Code + AL to develop for Dynamics 365 Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f345db93-dba7-9d68-e4fc-72333e569d20
* Version Independent ID: 9df47af2-6286-9a1b-724b-09b8866a620d
* Content: [Welcome to the Developer and IT-Pro Help for Microsoft Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/#feedback)
* Content Source: [dynamics-nav/index.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/index.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04

**Comment by edupont04** [comment]
Hello hindsight2020,
Thank you for your feedback! You're absolutely right, and we'll get that cleaned up with the next update.
