### ISSUE TITLE
No NAV version specified for which it is supported

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/navdevitpro-content-pr#2001]
Hi, 
there is no info for which NAV version and since which CU are these settings available. I landed on the page from search engine, and I do not have any clue, for which NAV version this page is created/valid.

Thanks!

Kamil Sacek
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9cccd9-adae-e7fc-3af2-db84d6453563
* Version Independent ID: 463291c2-470f-feff-6f22-7f3c0e25d5a6
* Content: [Configuring Query Hints for Optimizing SQL Server Performance with Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/sql-server-query-hints?source=docs#feedback)
* Content Source: [dynamics-nav/sql-server-query-hints.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/sql-server-query-hints.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The help that you find in this docset is applicable to Dynamics NAV 2018. We do not stamp every topic with versioning, but we introduce the docset [here](https://docs.microsoft.com/en-us/dynamics-nav/). Thanks.
