### ISSUE TITLE
ModalFormHandler should be ...

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/navdevitpro-content-pr#2004]
ModalPageHandler 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa98cf6d-5c86-0684-e5fb-a84e8e8b64d7
* Version Independent ID: 30f28213-6326-4a8c-6205-9e46bc13c6fd
* Content: [TRAP Function (TestPage) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/trap-function--testpage-)
* Content Source: [dynamics-nav/TRAP-Function--TestPage-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/TRAP-Function--TestPage-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks - will be fixed with the next refresh.
