### ISSUE TITLE
Upated information

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/navdevitpro-content-pr#2006]
Has Microsoft not spent any time developing RDLC reports in the last 4 years?
If not, what should we be using instead?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9612983e-fb87-6fbe-5098-70ce8823ef0e
* Version Independent ID: 64e6e787-a2af-34fb-51a6-21a88a24ea88
* Content: [Designing RDLC Report Layouts - Dynamics NAV](https://docs.microsoft.com/en-ca/dynamics-nav/Designing-RDLC-Report-Layouts)
* Content Source: [dynamics-nav/Designing-RDLC-Report-Layouts.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Designing-RDLC-Report-Layouts.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hello, you've reached the NAV documentation repo. For product-related questions, please contact your partner. Thanks.
