### ISSUE TITLE
Needs version supported information

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/navdevitpro-content-pr#2007]
On the old MSDN there used to be a drop down that would show you what the functionality looked like in other versions of NAV. I understand that going forward everything is BC, but until NAV customers upgrade, we're stuck helping with the issues they have.

For example, on this page, it would be amazing if I could immediately see that NAV 2016 has this deprecated and will not allow usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee717f2d-5193-e7dc-61af-dbc5de5cb17a
* Version Independent ID: 4237e653-4399-2055-d120-fe74b7c67cb3
* Content: [SAVEASHTML Function (Report) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/saveashtml-function--report-)
* Content Source: [dynamics-nav/SAVEASHTML-Function--Report-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SAVEASHTML-Function--Report-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by edupont04** [comment]
Hello mjmatthiesen,
Thank you for your feedback! Unfortunately, we are not able to generate automatic links between earlier versions of Dynamics NAV and NAV 2018 here on the Docs site. The team that manages the Docs.microsoft.com site welcomes contributions and suggestions here: https://github.com/MicrosoftDocs/feedback/issues 

For your information, the earlier versions are available in the Previous Versions section: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh174018(v=nav.90)
