### ISSUE TITLE
Include that the INIT function does *not* remove the CHANGECOMPANY reference.

### ISSUE THREAD

**Issue by ianscho** [MicrosoftDocs/navdevitpro-content-pr#2008]
From:
The CHANGECOMPANY function is not affected by the RESET Function (Record).
To:
The CHANGECOMPANY function is not affected by either the RESET Function (Record) nor the INIT Function (Record) .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 131fbbe9-d9a9-49b9-9729-f5ccf1275b2c
* Version Independent ID: 4a5e1ac4-6410-3c79-dc35-5fe2b303cb63
* Content: [CHANGECOMPANY Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/changecompany-function--record-#feedback)
* Content Source: [dynamics-nav/CHANGECOMPANY-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/CHANGECOMPANY-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback, this is fixed with the next doc refresh.
