### ISSUE TITLE
In Example, must be: MESSAGE(CustomerList.Name.Value);

### ISSUE THREAD

**Issue by d365nav** [MicrosoftDocs/navdevitpro-content-pr#2011]
In Example, must be: MESSAGE(CustomerList.Name.Value);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6033fb23-ddae-708c-71cd-ff41bbc04838
* Version Independent ID: 34a68e8e-4eff-0f1c-b3c0-27f39e1db113
* Content: [NEXT Function (TestPage) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/next-function--testpage-)
* Content Source: [dynamics-nav/NEXT-Function--TestPage-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/NEXT-Function--TestPage-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The topic will be fixed with the next refresh of the docs. Thanks!
