### ISSUE TITLE
Error in title)

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/navdevitpro-content-pr#2012]
Topic tiltel says: SELECTSTR Function (Code, Text). What does the last part, (Code, Text), mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94a7b774-52a0-3dfc-8082-101f0c573f90
* Version Independent ID: ba5fc698-f2e5-f1a7-c4b5-61464a0f347f
* Content: [SELECTSTR Function (Code, Text) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/selectstr-function--code--text-)
* Content Source: [dynamics-nav/SELECTSTR-Function--Code--Text-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SELECTSTR-Function--Code--Text-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Hi, the last part in brackets is the way we illustrate which data types the function applies to - in this case the Code data type and the Text data type. We use this notation in the NAV docset, but the Business Central docset is structured differently with regards to methods. Thanks.
