### ISSUE TITLE
"web service access key" links go to MS homepage

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/navdevitpro-content-pr#2013]
There are two instances (that I can find) of a link that read "web service access key" that go to https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-develop-connect-apps-for-fin. This links redirects to the Microsoft homepage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17c4eef7-2ff2-eeeb-d285-095002e99475
* Version Independent ID: 2beae6be-8b5f-2a48-4b68-81810248b8f6
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics#feedback)
* Content Source: [dynamics-nav/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this. The links should go to this doc: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#setting-up-basic-authentication.
The topic will be fixed with the next refresh of the docs.
