### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by samanat** [MicrosoftDocs/navdevitpro-content-pr#2015]
"Next, the FILTERGROUP function changes the filter group to 100. "
Should have been 
"Next, the FILTERGROUP function changes the filter group to 1. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 444fcd38-45db-3b22-becd-6d49e087c7dc
* Version Independent ID: f376d621-8714-2ede-f843-1448b8e47963
* Content: [FILTERGROUP Function (Record) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/filtergroup-function--record-#feedback)
* Content Source: [dynamics-nav/FILTERGROUP-Function--Record-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/FILTERGROUP-Function--Record-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This will be fixed with the next doc refresh.
