### ISSUE TITLE
Which property?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/navdevitpro-content-pr#2019]
" You would select RunObject in the PushAction property and use the RunObject Property to run the sales statistics page. In this property you could select Yes to display the same record on both pages." introduces the RunObject property and then immediately refers to "in this object". But the intended reference is to the RunPageOnRec property. Might be clearer to make this explicit: "Then in the RunPageOnRec property you could select Yes..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710e08ec-39a3-0b47-3715-22b97303e730
* Version Independent ID: 7b1a047a-ce32-2710-8d69-2a0b243d53ca
* Content: [RunPageOnRec Property - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/runpageonrec-property#feedback)
* Content Source: [dynamics-nav/RunPageOnRec-Property.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/RunPageOnRec-Property.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback, yes that could be made clearer - this will be fixed with the next doc refresh.
