### ISSUE TITLE
Dynamics 365 Business Central On-Prem Endpoint

### ISSUE THREAD

**Issue by louagej** [MicrosoftDocs/navdevitpro-content-pr#2021]
Dear,

For developers it's useful to add some more info to the url endpoint for On-Prem API's.
According the documentation the url is structured in this way.
![https://&lt;base URL&gt;:&lt;port&gt;/&lt;serverInstance&gt;/api/&lt;API version&gt;/]()
This is correct for the default API's made available by Microsoft.
When a partner develops its own API Page, the endpoint is structured this way:
![https://&lt;base URL&gt;:&lt;port&gt;/&lt;serverInstance&gt;/api/&lt;APIPublisher&gt;/&lt;APIGroup&gt;/&lt;API version&gt;/]()
The APIPublisher and APIGroup is found in the properties of the custom API page:
```AL
page 50000 "My Custom API"
{
    PageType = API;
    Caption = 'Custom API';
    APIPublisher = 'abc';
    APIGroup = 'xyz';
    APIVersion = 'v1.0';
   ...
```

Kind regards,
Job

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c2e0a70-16db-cebb-ff63-e7b0a5f4f70d
* Version Independent ID: 041169de-956b-f1a8-c66b-7bf77f5e5f64
* Content: [Endpoints for the APIs for Microsoft Dynamics NAV and Microsoft Dynamics 365 Business Central - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/endpoints-apis-for-dynamics.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback - this topic will be updated with the next doc refresh.
