### ISSUE TITLE
Wrong path in the docs

### ISSUE THREAD

**Issue by hkyshawn** [MicrosoftDocs/navdevitpro-content-pr#2026]
The documentation as of this comment states the endpoint path as 
"GET https://{businesscentralPrefix}/api/v1.0/companies({id})/customerPaymentsJournals({id})" 

This path yields an error "code": "BadRequest_NotFound", "message": "No HTTP resource was found that matches the request URI ...."

The correct endpoint path is:
"GET https://{businesscentralPrefix}/api/v1.0/companies({id})/customerPaymentJournals({id})"
Note that in the path segement "customerPaymentJournals" the text Payment is not pluralized. If you use the pluralized version it fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca0f63b-38bc-f707-77bd-e6a3189088c8
* Version Independent ID: 96244d97-f326-68fd-8a78-9911af389472
* Content: [Get customerPaymentsJournals - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_customerpaymentsjournal_get#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_customerpaymentsjournal_get.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_customerpaymentsjournal_get.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
thanks for catching this - it will be fixed with the next refresh of the docs. thanks!
