### ISSUE TITLE
Feature Limitations for Business Central SaaS Web Client

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/navdevitpro-content-pr#2028]
Hello
I cannot find any information about the BC web client's features limitations.
This page shows information only for Nav 2018 / Nav 2017.

Our customers want to switch from BC OnPrem Windows Client (BC v14) to BC OnPrem Web Client (BC v14) and need to know the "incompatibility" of the web client.

Can you help us ?
thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b3a845-b388-9c69-478f-87cc70b87819
* Version Independent ID: af209cd5-e554-fe3f-30f0-05d771b21a17
* Content: [Feature Limitations of the Web Client - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/feature-limitations-of-the-microsoft-dynamics-nav-web-client)
* Content Source: [dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Feature-Limitations-of-the-Microsoft-Dynamics-NAV-Web-Client.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by edupont04** [comment]
Hello @jnpatrouillault ,

There is no equivalent article for Dynamics 365 Business Central. While the Windows client is still available in version 14 on-premises, resources went into adding productivity features to the Web client. For more information, see the release plan for version 14 (https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-business-central/planned-features) and version 15 (https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/modern-clients).

Optionally, you can show them a demo of the latest version of Business Central online, which is very close to closing the last gaps.

**Comment by dnpb** [comment]
The lack of an equivalent article for BC causes questions such as
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1619878328786944

I could only say 'the NAV 2018 limitations probably still apply, mostly, maybe'... when really we should have a corresponding article about the modern BC Web Client, detailing which features that RTC-familiar developers will find are (still) missing.

**Comment by edupont04** [comment]
Hello Daniel,
We disagree on the subject, which is OK. As mentioned in several Yammer-threads, the modern clients are based on the web client, which has undergone many, many improvements in the past 5 years with far more capabilities than it had before. We're not going to publish a list of differences between the deprecated Windows client and the modern clients because it doesn't make sense. There are things user can do with the modern clients that they were not able to do with the Windows client; and there are things that don't make sense in a browser that made more sense in the installed client.

**Comment by dnpb** [comment]
You have a good point!

What makes more sense: all the things that are still accepted by the compiler, but will later at runtime fail or simply do nothing... should not be allowed to compile. I'll start opening separate issues on the AL repo for those.
