### ISSUE TITLE
In the Syntax example please change "GETDEFAULTCONNECTIONTYPE(Type)" to "GETDEFAULTTABLECONNECTION(Type)"

### ISSUE THREAD

**Issue by ianscho** [MicrosoftDocs/navdevitpro-content-pr#2029]
The following is a typo in the Syntax section, which causes an error when copied and carried across to the NAV development environment:
  Name:= GETDEFAULTCONNECTIONTYPE(Type)  

Please change to:
  Name:= GETDEFAULTTABLECONNECTION(Type)  

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5929675c-2a0e-3544-8141-0402a047a173
* Version Independent ID: c5c58a46-c50a-315a-e368-9eba44fff632
* Content: [GETDEFAULTTABLECONNECTION Function (Database) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/getdefaulttableconnection-function--database-)
* Content Source: [dynamics-nav/GETDEFAULTTABLECONNECTION-Function--Database-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/GETDEFAULTTABLECONNECTION-Function--Database-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this - will be fixed with the next refresh of the docs.
