### ISSUE TITLE
Misleading example - delete the ELSE statement

### ISSUE THREAD

**Issue by GrumpyNAVdev** [MicrosoftDocs/navdevitpro-content-pr#2047]
Guidelines say you should never have an ELSE efter EXIT, and in this case CurrReport.SKIP is simular.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019f2992-05c3-dd34-ec26-231a84e1034b
* Version Independent ID: d9382aeb-d9e5-8e15-2941-0e2674c27978
* Content: [SKIP Function (Report, XMLport) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/skip-function--report--xmlport-)
* Content Source: [dynamics-nav/SKIP-Function--Report--XMLport-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/SKIP-Function--Report--XMLport-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for your feedback, this will be fixed soon.
