### ISSUE TITLE
Topic depricated for Business Central?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/navdevitpro-content-pr#2057]
Mybe I am overlooking something, but it seems this topic has been depricated for BC. It would really appreciate it this was reverted. This info is of great value and there is no matching replacement for is it.
I know https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extension-advanced-example-test is mention it, but with less info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceab92c1-9510-ed55-8bac-41b1614ebfb0
* Version Independent ID: 93786902-1621-bfd0-03f4-4dbb5bf35f11
* Content: [Create Handler Functions - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--create-handler-functions)
* Content Source: [dynamics-nav/How-to--Create-Handler-Functions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Create-Handler-Functions.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by lvanvugt** [comment]
This is more than a month old and no response. When can I expect this?

**Comment by SusanneWindfeldPedersen** [comment]
This has been ported. Closing issue.
