### ISSUE TITLE
Sub Type

### ISSUE THREAD

**Issue by MarkCWEV** [MicrosoftDocs/navdevitpro-content-pr#2064]
Shouldn't the sub type be "Customer Card"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52aed69-f6b0-c9cc-e6a4-a5ef7ed518ca
* Version Independent ID: d240e27a-4bc2-c03c-de9c-c062eebfbed2
* Content: [OPENNEW Function (TestPage) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/opennew-function--testpage-#feedback)
* Content Source: [dynamics-nav/OPENNEW-Function--TestPage-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/OPENNEW-Function--TestPage-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. Yes, the subtype should be Customer Card - this will be fixed with the next refresh of the docs.
