### ISSUE TITLE
a small spelling mistake

### ISSUE THREAD

**Issue by GUBLAZ** [MicrosoftDocs/navdevitpro-content-pr#2072]
Hi,

I believe that the Windows Server described, in point 2, is not version "2912" but Windows Server 2012?

kr
Haiko

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606d0a6-c405-9c37-6e51-141ad731f98d
* Version Independent ID: dc0bea73-4cbf-5715-c7bc-595f1174b1f2
* Content: [Administer Multiple Server Computers - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--administer-multiple-microsoft-dynamics-nav-server-computers#feedback)
* Content Source: [dynamics-nav/How-to--Administer-Multiple-Microsoft-Dynamics-NAV-Server-Computers.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Administer-Multiple-Microsoft-Dynamics-NAV-Server-Computers.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, this will be fixed soon, thanks.
