### ISSUE TITLE
Payment Terms

### ISSUE THREAD

**Issue by markjourdan** [MicrosoftDocs/navdevitpro-content-pr#2075]
In the example you have "paymentTermsId". This is not a parameter that can be used to create a purchase invoice. Only the following are acceptable.

&lt;EntityType Name="purchaseInvoice"&gt;
&lt;Key&gt;
&lt;PropertyRef Name="id"/&gt;
&lt;/Key&gt;
&lt;Property Name="id" Type="Edm.Guid" Nullable="false"/&gt;
&lt;Property Name="number" Type="Edm.String" MaxLength="20"/&gt;
&lt;Property Name="invoiceDate" Type="Edm.Date"/&gt;
&lt;Property Name="postingDate" Type="Edm.Date"/&gt;
&lt;Property Name="dueDate" Type="Edm.Date"/&gt;
&lt;Property Name="vendorInvoiceNumber" Type="Edm.String" MaxLength="35"/&gt;
&lt;Property Name="vendorId" Type="Edm.Guid"/&gt;
&lt;Property Name="vendorNumber" Type="Edm.String" MaxLength="20"/&gt;
&lt;Property Name="vendorName" Type="Edm.String" MaxLength="100"/&gt;
&lt;Property Name="payToName" Type="Edm.String" MaxLength="100"/&gt;
&lt;Property Name="payToContact" Type="Edm.String" MaxLength="100"/&gt;
&lt;Property Name="payToVendorId" Type="Edm.Guid"/&gt;
&lt;Property Name="payToVendorNumber" Type="Edm.String" MaxLength="20"/&gt;
&lt;Property Name="shipToName" Type="Edm.String" MaxLength="100"/&gt;
&lt;Property Name="shipToContact" Type="Edm.String" MaxLength="100"/&gt;
&lt;Property Name="buyFromAddress" Type="Microsoft.NAV.postalAddressType"/&gt;
&lt;Property Name="payToAddress" Type="Microsoft.NAV.postalAddressType"/&gt;
&lt;Property Name="shipToAddress" Type="Microsoft.NAV.postalAddressType"/&gt;
&lt;Property Name="currencyId" Type="Edm.Guid"/&gt;
&lt;Property Name="currencyCode" Type="Edm.String"/&gt;
&lt;Property Name="pricesIncludeTax" Type="Edm.Boolean"/&gt;
&lt;Property Name="discountAmount" Type="Edm.Decimal" Scale="Variable"/&gt;
&lt;Property Name="discountAppliedBeforeTax" Type="Edm.Boolean"/&gt;
&lt;Property Name="totalAmountExcludingTax" Type="Edm.Decimal" Scale="Variable"/&gt;
&lt;Property Name="totalTaxAmount" Type="Edm.Decimal" Scale="Variable"/&gt;
&lt;Property Name="totalAmountIncludingTax" Type="Edm.Decimal" Scale="Variable"/&gt;
&lt;Property Name="status" Type="Edm.String"/&gt;
&lt;Property Name="lastModifiedDateTime" Type="Edm.DateTimeOffset"/&gt;
&lt;NavigationProperty Name="purchaseInvoiceLines" Type="Collection(Microsoft.NAV.purchaseInvoiceLine)" ContainsTarget="true"/&gt;
&lt;NavigationProperty Name="pdfDocument" Type="Collection(Microsoft.NAV.pdfDocument)" ContainsTarget="true"/&gt;
&lt;NavigationProperty Name="vendor" Type="Microsoft.NAV.vendor" ContainsTarget="true"/&gt;
&lt;NavigationProperty Name="currency" Type="Microsoft.NAV.currency" ContainsTarget="true"/&gt;
&lt;/EntityType&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1acc899a-683d-87c3-2762-097b4fb1643f
* Version Independent ID: 961e1386-5a77-1fb8-dfa7-20c716e0b982
* Content: [Create purchaseInvoices - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_create_purchaseinvoice#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_create_purchaseinvoice.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_create_purchaseinvoice.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This is fixed with the next refresh of the docs.
