### ISSUE TITLE
Requires NAV 2016 or newer versions

### ISSUE THREAD

**Issue by Kowa63** [MicrosoftDocs/navdevitpro-content-pr#2077]
To use BREAK in Repeat-Until requires NAV 2016 or newer versions. That should be mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d430cf5a-414c-8565-755f-52ef527acad6
* Version Independent ID: a22533d2-9fe9-87bd-fb1c-6e586da0e3e4
* Content: [C/AL BREAK Statement - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/c-al-break-statement)
* Content Source: [dynamics-nav/C-AL-BREAK-Statement.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/C-AL-BREAK-Statement.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by sweikelt** [comment]
would be a nice feature!

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The documentation in this repo applies to Microsoft Dynamics NAV 2018. To find documentation for earlier versions, please go [here](https://docs.microsoft.com/en-us/previous-versions/dynamics/)

**Comment by Kowa63** [comment]
Thanks for the link, but the documentation for older versions will likewise not mention unsupported commands in C/AL which were introduced in the later versions. Is there any other documentation or overview about which version of NAV allows which commands?

**Comment by edupont04** [comment]
Hello Kai,
As Susanne said, this set of NAV docs is for NAV 2018. Earlier versions are found here: https://docs.microsoft.com/en-us/previous-versions/dynamics/. And of course, AL docs show latest version [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dev-overview), as I'm sure you know already.
The C/AL Break statement was first added here: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/dn951447(v=nav.90) and is not mentioned under NAV 2015, for example: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2015/dd355277(v=nav.80)
