### ISSUE TITLE
Available methods

### ISSUE THREAD

**Issue by atotovic** [MicrosoftDocs/navdevitpro-content-pr#2079]
Why we have only GET method for Account, as in daily work there is often a situation users need CREATE and UPDATE as well? There is not such a big benefit with only GET method for Accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e1778f3-b226-cafd-de3c-7995491395eb
* Version Independent ID: 56f4c2a6-8e48-7901-7af1-6c2bb2c6eae2
* Content: [accounts resource type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/resources/dynamics_account#feedback)
* Content Source: [dynamics-nav/api-reference/v1.0/resources/dynamics_account.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/resources/dynamics_account.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
