### ISSUE TITLE
Why hasn't this topic be ported to BC docs?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/navdevitpro-content-pr#2081]
Maybe I am overlooking something, but it seems this topic does not exist as BC topic. Please include it there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7a572bd-8d8f-37c6-86e7-ba74ce61e93e
* Version Independent ID: 405f936b-7b89-c5d8-d9e0-76d201354f55
* Content: [Handling Errors by Using Try Functions - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/handling-errors-by-using-try-functions)
* Content Source: [dynamics-nav/Handling-Errors-by-Using-Try-Functions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Handling-Errors-by-Using-Try-Functions.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This topic will be part of the BC docs with the next doc refresh.
