### ISSUE TITLE
Link in "Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md" to "Web Service Alternatives" page is malformed

### ISSUE THREAD

**Issue by kdx-perbol** [MicrosoftDocs/navdevitpro-content-pr#2090]
Link in `Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md` to "Web Service Alternatives" page is malformed hence cannot be resolved when building docs. 

Link at bottom

`Web-Service-Alternatives:-SOAP-and-OData.md`

should be

`Web-Service-Alternatives--SOAP-and-OData.md`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ab2d51-62c3-fa9a-7a3f-556097ef3c43
* Version Independent ID: a93c5d06-2ca9-f8d5-7b49-b69429e7f613
* Content: [Walkthrough: Creating and Interacting with a Page Web Service (OData) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--creating-and-interacting-with-a-page-web-service--odata-)
* Content Source: [dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Creating-and-Interacting-with-a-Page-Web-Service--OData-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Thanks for the feedback! The link has been fixed and an update will be published soon.
