### ISSUE TITLE
Why is this topics not ported to BC documentation?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/navdevitpro-content-pr#2092]
Why is this topics not ported to BC documentation? I think it makes sense to have it there too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428a2986-828d-37d1-4c3e-7ef0908ddf67
* Version Independent ID: 6fb4c386-4a87-b83a-e5f9-6ffb82c48cf1
* Content: [Temporary Tables - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/temporary-tables)
* Content Source: [dynamics-nav/Temporary-Tables.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Temporary-Tables.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
The topic has now been ported to the Business Central docs [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-runobject-property). Thanks.

**Comment by lvanvugt** [comment]
@SusanneWindfeldPedersen the link you shared does not relate to my issue. So what's the case? Wrong link or issue not solved?

**Comment by SusanneWindfeldPedersen** [comment]
Sorry, it should be this link: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-temporary-tables
