### ISSUE TITLE
Incorrect info

### ISSUE THREAD

**Issue by Blueyesdragon** [MicrosoftDocs/navdevitpro-content-pr#2094]
GET businesscentralPrefix/companies({id})/salesInvoices({id}) is incorrect

Proper way is : GET businesscentralPrefix/companies({id})/salesInvoices('{id}')
(Added single quotes with document line id)

Note : the improper example seems to be on all GET/PATCH/DELETE document/line({id}) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63931266-e463-ab1e-5f15-6cba4a0cc9b5
* Version Independent ID: a1fa5e63-49a6-ada2-1d9c-8d2d7341f08e
* Content: [Get salesInvoiceLines - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_salesinvoiceline_get)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_salesinvoiceline_get.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_salesinvoiceline_get.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. {id} does not stand for a literal string, you should replace it with an actual entity id. That's why it's not in quotes.
