### ISSUE TITLE
Error in URL exemple

### ISSUE THREAD

**Issue by Blueyesdragon** [MicrosoftDocs/navdevitpro-content-pr#2095]
Incorrect : PATCH businesscentralPrefix/companies({id})/salesInvoices({id})/salesInvoiceLines({salesOrderLineId})

salesOrderLineId needs to be replace by salesInvoiceLineId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25296d1-a1ad-6f46-b1d2-41bad1a61cd6
* Version Independent ID: e6aa4752-c343-e5cd-e03f-38f3ec67093b
* Content: [Update salesInvoiceLines - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_salesinvoiceline_update)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_salesinvoiceline_update.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_salesinvoiceline_update.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This will be fixed with the next refresh.
