### ISSUE TITLE
"This week has three days in 2008 and four days in 2014. Therefore, the output year is 2014."

### ISSUE THREAD

**Issue by urjuhh** [MicrosoftDocs/navdevitpro-content-pr#2097]
Be careful, when reusing old documentation with dates in it ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67161030-3094-5537-a275-ab813d92eff0
* Version Independent ID: ac5e93e8-29fb-a652-b975-3c09ed443aa4
* Content: [DATE2DWY Function (Date) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/date2dwy-function--date-)
* Content Source: [dynamics-nav/DATE2DWY-Function--Date-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/DATE2DWY-Function--Date-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This will be fixed with the next refresh.
