### ISSUE TITLE
forgot '?' in front of the $-sign

### ISSUE THREAD

**Issue by woutertrappers** [MicrosoftDocs/navdevitpro-content-pr#2100]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e8e045-c704-ff20-36d9-4a1cfa874f43
* Version Independent ID: 21537b68-a8eb-1377-60b7-ea54e5661ff3
* Content: [Get timeRegistrationEntries - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/api/dynamics_timeregistrationentry_get)
* Content Source: [dynamics-nav/api-reference/v1.0/api/dynamics_timeRegistrationEntry_get.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v1.0/api/dynamics_timeRegistrationEntry_get.md)
* Service: **dynamics365-businesscentral**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. This will be fixed with the next refresh.
