### ISSUE TITLE
Please correct label "For more information, see System Requirements for Microsoft Dynamics NAV 2017." - Link is to Nav 2018

### ISSUE THREAD

**Issue by BernhardRaether** [MicrosoftDocs/navdevitpro-content-pr#2162]
The Label in this Document says "For more information, see System Requirements for Microsoft Dynamics NAV 2017."
The link is https://docs.microsoft.com/en-us/dynamics-nav/system-requirements-for-microsoft-dynamics-nav
and lands on a NAV 2018 page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aeba421-f337-0127-0f39-5acc7d2f12e1
* Version Independent ID: b9f97b15-ecbc-6077-922f-a3e1e11804cd
* Content: [How to: Prepare Dynamics 365 for Sales for Integration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to-prepare-dynamics-crm-for-integration)
* Content Source: [dynamics-nav/How-to-prepare-Dynamics-CRM-for-Integration.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to-prepare-Dynamics-CRM-for-Integration.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by BernhardRaether** [comment]
Seems that six month wasn't enough to get someone assigned, hope this comment helps.

**Comment by jswymer** [comment]
Thanks for the feedback! The link label has been fixed. The update will be published soon.
