### ISSUE TITLE
Deduct and alsmust typos

### ISSUE THREAD

**Issue by DavidRoys** [MicrosoftDocs/navdevitpro-content-pr#2165]
[Enter feedback here]

"deduct" should be "deduce" in
"If this parameter is not specified, the function will deduct the MIME type from the file extension. For example the MIME type for a .jpg file is image/jpeg."

"alsmust" should be "must also" in "In support of the example code, you alsmust complete these tasks:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b33da934-cdb3-ddf3-0fce-07719474bd3c
* Version Independent ID: c786189b-3482-1442-b8a3-29296d500a4c
* Content: [IMPORTFILE Function (MediaSet) - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/importfile-function--mediaset-)
* Content Source: [dynamics-nav/IMPORTFILE-Function--MediaSet-.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/IMPORTFILE-Function--MediaSet-.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The issues have been fixed and the updated article will be published soon.
