### ISSUE TITLE
Broken link PATCH under "Renewing the subscription"

### ISSUE THREAD

**Issue by jwikman** [MicrosoftDocs/navdevitpro-content-pr#2197]
The link to `PATCH` (https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v2.0/api/dynamics_subscription_update.md) in header [Renewing the subscription](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v2.0/dynamics_subscriptions#renewing-the-subscription) seems to be broken.

edit: also the following links are broken (and I might have missed some😉) :
* `subscription` in header [Renewing the subscription](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v2.0/dynamics_subscriptions#renewing-the-subscription) 
* `delete request` in [Unsubscribing](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v2.0/dynamics_subscriptions#unsubscribing) 

Cheers,
Johannes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83afd88b-59f5-9368-da9c-385d2fccc524
* Version Independent ID: 92ccc0b9-3528-9eab-39bf-5ba7c9fbdcff
* Content: [Working with Webhooks - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v2.0/dynamics_subscriptions)
* Content Source: [dynamics-nav/api-reference/v2.0/dynamics_subscriptions.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/api-reference/v2.0/dynamics_subscriptions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. This was due to a rename of the api files. Will be fixed with the next refresh of the docs. Thanks.
