### ISSUE TITLE
Version wrongly refers to 10.0.0.0

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/navdevitpro-content-pr#2211]
[Enter feedback here]
Versions of DotNet components wrongly refer to 10.0.0.0 - correct file versions for NAV 2018 are 11.0.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a0b3e9-6311-cb43-e0d4-bb1f53432bfb
* Version Independent ID: 58f2b2be-0b9f-aae9-e191-7c964055f313
* Content: [Resolving Codeunit 1410 Doc. Exch. Service Mgt. Error When Converting a Database - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/resolve-cu1410-doc-exch-service-mgt-compilation-error)
* Content Source: [dynamics-nav/Resolve-CU1410-Doc-Exch-Service-Mgt-Compilation-Error.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Resolve-CU1410-Doc-Exch-Service-Mgt-Compilation-Error.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been fixed and an update will be published soon.
