### ISSUE TITLE
Misc typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/navdevitpro-content-pr#2228]
The following line
contains data about the pages in database.
should be
contains data about the **reports** in **the** database.

The following line
The fields in the virtual table correspond to C/AL properties on the page objects. 
should be
The fields in the virtual table correspond to C/AL properties on the **report** objects. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58260c19-af02-28ca-5809-3ffb6c420b4b
* Version Independent ID: c59ce1ec-638b-3a95-a74b-9641a633f977
* Content: [Report Metadata Virtual Table - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/report-metadata-virtual-table)
* Content Source: [dynamics-nav/Report-Metadata-Virtual-Table.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Report-Metadata-Virtual-Table.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. The article has been fixed and an update will be published soon.
